Add updatecli with a basic validation
rancher/system-agent-installer-k3s pull request #18
Opened 2023-03-31 20:57 UTC by matttrach

This introduces updatecli to the repo, contributing to https://github.com/k3s-io/k3s/issues/7040.

2023-04-01 01:10 UTC, brandond approved these changes

2023-04-03 12:31 UTC, macedogm requested changes

2023-04-03 12:31 UTC, macedogm commented on .github/workflows/updatecli.yml
> +    if: github.ref == 'refs/heads/master'
```suggestion
    if: github.ref == 'refs/heads/main'
```

2023-04-03 12:31 UTC, macedogm commented on .github/workflows/updatecli.yml
> +    if: github.ref == 'refs/heads/master'
This repo uses the `main` branch.

2023-04-03 14:29 UTC, matttrach commented on .github/workflows/updatecli.yml
> +    if: github.ref == 'refs/heads/master'
good catch! onit

2023-04-03 15:14 UTC, macedogm approved these changes

2023-04-03 16:26 UTC, merged